### ISSUE TITLE
Prevent self-TL;DR

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/tldr#8] opened 2023-06-09 06:50 UTC
> ![It hurt itself in its confusion!](https://cdn.discordapp.com/attachments/791524856927223809/1116620087835775046/cover5.png)

Currently, the TL;DR function has the potential to generate a summary of its own message, which results in redundancy and confusion in the LLM (Language Model). To address this problem, we propose implementing a verification process that compares the ID of the author of the target message with the bot's ID. By excluding the bot's ID from the TL;DR process, we can avoid self-TL;DR and enhance the overall effectiveness of this feature.

### Mitigation

To prevent self-TL;DR and improve the effectiveness of the TL;DR function, we suggest implementing a verification process. This process would involve comparing the ID of the author of the target message with the bot's ID. By excluding the bot's ID from the TL;DR process, we can ensure that the function doesn't generate a summary of its own message. This will eliminate redundancy and confusion in the LLM.

**Comment by jjoeldaniel** [comment] 2023-06-09 07:33
Duplicate of #7

**Closed as not planned by jjoeldaniel** 2023-06-09 07:33 UTC
Labels: bug, enhancement
